# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('projector', 'Projector'), ('tablet', 'Tablet'), ('headset', 'Headset'), ('hard_drive', 'Hard Drive'), ('webcam', 'Web Cam'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], max_length=16)),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spare', 'Spare'), ('retired', 'Retired')], default='active', max_length=16)),
                ('description', models.TextField(blank=True, help_text='Any additional description of the device if necessary', null=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='EventBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('link', models.URLField(blank=True, help_text='A link to more information.', null=True)),
                ('documentation', models.FileField(blank=True, null=True, upload_to=b'')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'ordering': ['-end_date'],
                'verbose_name_plural': 'Warranties',
            },
        ),
        migrations.CreateModel(
            name='DecommissionEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('method', models.CharField(choices=[('recycled', 'Recycled'), ('sold', 'Sold'), ('disposal service', 'Disposal Service')], max_length=16)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=b'')),
                ('cost', models.FloatField(help_text='\n        Use positive values when selling, negative if paying a service.\n        ')),
            ],
            options={
                'verbose_name': 'Decommission',
            },
            bases=('devices.eventbase',),
        ),
        migrations.CreateModel(
            name='LossEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('documentation', models.FileField(blank=True, null=True, upload_to=b'')),
                ('recovery_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loss',
            },
            bases=('devices.eventbase',),
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
            ],
            options={
                'verbose_name': 'Note',
            },
            bases=('devices.eventbase',),
        ),
        migrations.CreateModel(
            name='PurchaseEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('vendor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_website', models.URLField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=b'')),
                ('purchased_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'verbose_name': 'Purchase',
            },
            bases=('devices.eventbase',),
        ),
        migrations.CreateModel(
            name='RepairEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('cost', models.FloatField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to=b'')),
                ('vendor_name', models.CharField(max_length=128)),
                ('vendor_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Repair',
            },
            bases=('devices.eventbase',),
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('transferred_from', models.ForeignKey(blank=True, help_text='\n        Leave blank if this came from the spare inventory.\n        ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfered_from', to='people.Person')),
                ('transferred_to', models.ForeignKey(blank=True, help_text='\n        Leave blank if leaving as a spare.\n        ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfered_to', to='people.Person')),
            ],
            options={
                'verbose_name': 'Transfer',
            },
            bases=('devices.eventbase',),
        ),
        migrations.AddField(
            model_name='eventbase',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.Device'),
        ),
    ]
