# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbase',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='noteevent',
            options={'verbose_name': 'Note'},
        ),
        migrations.AddField(
            model_name='device',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventbase',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.Device'),
        ),
    ]
