# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20161115_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferevent',
            old_name='transfered_from',
            new_name='transferred_from',
        ),
        migrations.RenameField(
            model_name='transferevent',
            old_name='transfered_to',
            new_name='transferred_to',
        ),
    ]
