# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20161121_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='retired',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('spare', 'Spare'), ('retired', 'Retired')], default='active', max_length=16),
        ),
    ]
