# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20161205_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='decommissionevent',
            name='retired_device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
