# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20161121_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decommissionevent',
            options={'verbose_name': 'Decommission'},
        ),
        migrations.AlterModelOptions(
            name='lossevent',
            options={'verbose_name': 'Loss'},
        ),
        migrations.AlterModelOptions(
            name='repairevent',
            options={'verbose_name': 'Repair'},
        ),
        migrations.AlterModelOptions(
            name='transferevent',
            options={'verbose_name': 'Transfer'},
        ),
        migrations.AlterField(
            model_name='device',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
