# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20161128_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='notes',
        ),
    ]
