# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20170101_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decommissionevent',
            name='retired_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
