# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, help_text='Any additional description of the device if necessary', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('printer', 'Printer'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('projector', 'Projector'), ('tablet', 'Tablet'), ('headset', 'Headset'), ('hard_drive', 'Hard Drive'), ('webcam', 'Web Cam'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], max_length=16),
        ),
    ]
