# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20161129_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='notes',
        ),
    ]
