# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_warranty_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEvent',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.EventBase')),
                ('vendor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_website', models.URLField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'verbose_name': 'Purchase',
            },
            bases=('devices.eventbase',),
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['-end_date'], 'verbose_name_plural': 'Warranties'},
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('projector', 'Projector'), ('tablet', 'Tablet'), ('headset', 'Headset'), ('hard_drive', 'Hard Drive'), ('webcam', 'Web Cam'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], max_length=16),
        ),
        migrations.AddField(
            model_name='PurchaseEvent',
            name='purchased_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
