# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:55
from __future__ import unicode_literals

from django.db import migrations


def create_purchases(apps, schema_editor):
    # Move `Device` purchase fields to `PurchaseEvent`
    Device = apps.get_model("devices", "Device")
    PurchaseEvent = apps.get_model("devices", "PurchaseEvent")
    for device in Device.objects.all():
        if device.date_purchased:
            PurchaseEvent.objects.create(
                event_type='purchase',
                device=device,
                purchased_device=device,
                date=device.date_purchased,
                purchase_price=device.purchase_price,
                receipt=device.receipt,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20161130_2254'),
    ]

    operations = [
        migrations.RunPython(create_purchases),
    ]
