# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20161130_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='device',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='device',
            name='receipt',
        ),
    ]
