# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20161128_0705'),
    ]

    database_operations = [
        migrations.AlterModelTable('Person', 'people_person')
    ]

    state_operations = [
        migrations.DeleteModel('Person')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
