# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('people', '0002_person_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_start', models.IntegerField(default=3)),
                ('laptop_end', models.IntegerField(default=5)),
                ('desktop_start', models.IntegerField(default=3)),
                ('desktop_end', models.IntegerField(default=5)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
    ]
